bot:
  test: Привет! (bot)
springdoc:
  swagger-ui:
    path: "/swagger-ui"
rabbitmq:
  exchange-name: my-exchange
  queue-name: my-queue
  routing-key: my-routing-key
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
name: Bot Build

on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    name: Build Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Bot
        run: mvn package -pl bot -am
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./bot.Dockerfile
          tags: bot:latest
